---
title: "Datasci for lang & mind"
subtitle: "Tuesdays and Thursdays COHN 402"

---
 <!-- resources:  -->

- contact: [katie](mailto:kschuler@sas.upenn.edu), [june](mailto:yjchoe@sas.upenn.edu), [avinash](mailto:amgoss@sas.upenn.edu), [ravi](mailto:raviarya@sas.upenn.edu)
- resources: [ed](https://edstem.org/us/courses/41903/discussion/), [canvas](https://canvas.upenn.edu/courses/1736107), [gradescope](https://www.gradescope.com/courses/561597), [colab](https://colab.research.google.com/#create=true&language=r)


Week | Day | Topic | Resources |
|- |-|-----|----|
| 1 | 08-28 | [Hello, world!](notes/hello-world.qmd) | [slides](/slides/hello-world.qmd)|  
| 1 | 08-31 | [R-basics](/notes/r-basics.qmd)  | [slides](/slides/r-basics.qmd), [demo](https://colab.research.google.com/drive/1WjgmOFe5yg6ylrjZd2aoqX1W_rrCXTz9?usp=sharing), [lab](labs/lab-01.qmd)| 
| 2 | 09-05 |  [Data importing](/notes//data-importing.qmd)  | [slides](/slides/data-importing.qmd), [demo](https://colab.research.google.com/drive/1xHEa4cT99JO5Bnh3RroMphCyt3DLjpxT?usp=sharing)| 
| 2 | 09-07 |   [Data visualization](/notes/data-visualization.qmd) | [slides](/slides/data-visualization.qmd), [demo](https://colab.research.google.com/drive/1B3VInRhxnq4rL5RPlW4CnNDpWUeo0KS2?usp=sharing), [lab](/labs/lab-02.qmd) |
| 2 | 09-10 |   [Problem set 1](/psets/problem-set-01.qmd) | [solutions](https://colab.research.google.com/drive/1SE3nfYFeY3hvWVjmn2fNYtzNCVaaTQLM?usp=sharing) |
|  3 | 09-12 |   More data visualization | see 09-07, [demo](https://colab.research.google.com/drive/1_gPlVNnI_SnTG3gL0YcLXEirCPKuyrfx?usp=sharing) |
|  3 | 09-14 |  [Data wrangling](/notes/data-wrangling.qmd) | [slides](/slides/data-wrangling.qmd), [lab](/labs/lab-03.qmd) | 
|  4 | 09-19 |  [Quiz 1](/quizzes/quiz-01.qmd) | [study guide](/quizzes/quiz-study-guide.qmd), [solutions](/quizzes/quiz-01-solutions.qmd) |
| 4 | 09-20 |  [Sampling distribution](/notes/sampling-distribution.qmd) | [slides](/slides/sampling-distribution.qmd), [lab](/labs/lab-04.qmd) | 
|  5 | 09-26 | **Class cancelled** |  | 
|  5 | 09-28 |  [Hypothesis testing](/notes/hypothesis-testing.qmd) | [slides](/slides/hypothesis-testing.qmd), [demo](https://colab.research.google.com/drive/1x9vpKr2zqnDEzsMnBfQvU2h5h_X5kzN_) | 
| 5 | 10-03 |  [Problem set 2](/psets/problem-set-02.qmd) || 
| 6 | 10-03 |  [Model specification](/notes/model-specification.qmd) | [slides](/slides/model-specification.qmd) | 
| 6 | 10-05 |  [Quiz 2 review](https://colab.research.google.com/drive/1TwLVKtgUzVV09qnky_9YAAUOlDNArXno?usp=sharing) | [practice quiz](/labs/lab-06.qmd)| 
| 7 | 10-10 |  [Quiz 2](/quizzes/quiz-02.qmd) | [solutions](/quizzes/quiz-02-solutions.qmd) | 
| 7 | 10-12 |  **No class, break** | | 
| 8 | 10-17 |  Model fitting | [slides](/slides/model-fitting.qmd) | 
| 8 | 10-19 |  Model fitting tutorial| | 
| 9 | 10-24 | Model accuracy | | 
| 9 | 10-26 |  Model accuracy tutorial | | 
| 9 | 10-26 | [Problem set 3](/psets/problem-set-03.qmd) | | 
| 10 | 10-31 | Quiz 3 review | | 
| 10 | 11-02 |  Quiz 3 (thursday!) | | 
| 11 | 11-07 | Model reliability | | 
| 11 | 11-09 |  Model reliability tutorial | | 
| 11 | 11-12 |  Problem set 4 | | 
| 12 | 11-14 |  Classification | | 
| 12 | 11-16 |  tutorial / review | | 
| 13 | 11-21 |  Quiz 4 | | 
| 13 | 11-23 |  **No class, break** | | 
| 14 | 11-28 | Inference | | 
| 14 | 11-30 | Feature engineering | | 
| 14 | 12-03 | Problem set 5 | | 
| 15 | 12-05 | Multilevel models | | 
| 15 | 12-07 | R tutorial| | 
| 15 | 12-10 | Problem set 6 | | 

