---
title: "Rubric"
subtitle: "Grading rubric for problem sets and quizzes"
number-sections: false

---

All quiz and problem set questions are graded with the following 4-point rubric. By "understand" we mean you understand the lecture concepts and can apply the technical skills you learned in the course.  Solutions that include packages or functions not covered in this course will recieve a highest possible score of 2.

| Score | % | Meaning | Description
|-|-|--|-------|
| **4** | 100% | **Exceptional!** | You show mastery of the course material and can perfectly apply all relevant skills to this problem. |
| **3** | 90% | **Well done!** | You understand the course material and can do all parts of this problem yourself with some room for improvement in code and/or reasoning. |
| **2** | 80% | **Getting there** | You have some gaps in your understanding of the course material and can do some parts of this problem, but you need a little more practice to get there. |
| **1** | 70% | **Just starting** | You have lots of gaps in your understanding of the course material and could not do most of this problem. You need a lot more practice to get there. |
| **0** | 60% | **Not complete** | You left this question completely blank |


## Overall grade
To compute your overall grade on a problem set or quiz, we take your *average* score on all questions, add a constant of 6, and divide by 10. For example, given a problem set with 3 questions:

- scores of 4-3-3 would result in a 93.3% (A): (4+3+3)/3 + 6 = 9.33/10
- scores of 3-2-2 would result in a 83.3% (B-): (3+2+2)/3 + 6 = 8.33/10
- scores of 1-1-1 would result in a 70% (C-): (1+1+1)/3 + 6 = 7/10

We chose this rubric because all reasonable attempts receive a passing grade, but A+ is reserved for students with advanced understanding of the material. 

## Missed problem sets and quizzes

Missed problem sets or quizzes will receive an overall score of zero. However, students can submit any missed problem set or quiz by the end of the semester for half credit (50%).



