---
layout: post
title:  "Lab 1: Getting started with R"
date:   2023-08-29 17:37:08 -0400
author: Katie Schuler
categories: "Practice problems"
---

To learn to program in R (or any language), you can read about how to do it, and watch someone else do it; but the only way to really learn is to do it yourself. Create some data structures, try some stuff, and see what happens! Here are some practice quiz questions to guide your learning. We will go over the solutions to these in lab.

## R Basics


1. Which of the following are expressions? Choose all that apply.
    - `10`
    - `5 + 10`
    - `x <- 5 + 10`
    - `x <- y + 10`
    - `mean(x)`

1. Which of the following are valid variable names in R? 
    - `childAge`
    - `response_time`
    - `1stPlaceWinner`
    - `2fast2furious`
    - `fast&furious`

1. Suppose we run the following code block. What will `ls()` return? 

    ```r
    x <- mean(1, 3, 5)
    y <- median(1, 3, 5)
    ```

1. Suppose we run `library(tidyverse)` in Google Colab and receive the following error message? How do we solve this problem? 

    > `NameError: name 'library' is not defined`

## Vectors

1. The expression `attributes(x)` returns the following result. What will `typeof(x)` return?  

    > `$dim= 2 . 2`

1. Suppose we run the following code block. What will `typeof(x)` return? 

    ```r
    x <- c()
    ```


1. Explain in one sentence the difference between an atomic vector and a list. 

1. Suppose we run the following code block. What will `typeof(x)` return? What about `length(x)`? Explain why.

    ```r
    x <- data.frame(x=c(1,2,3), y=c("a","b","c"))
    ```

1. Suppose we run the following code. What will `y` return? What about `typeof(y)`?

    ```r
    x <- c(2,4,6)
    y <- x * 2   
    ```

## Subsetting
1. Suppose we run the following code. What will each of operations return (a - e)? 

    ```r
    x <- seq(2:8, by=2)
    ```
    a. `x[c(2,4)]`
    b. `x[-c(2,4)]`
    c. `x[]`
    d. `x[[2]]`
    e. `x[2]`

1. Suppose `m` is a matrix created with `matrix(c(1,2,3,4), nrow=2, ncol=2)`. What will each of the following operations return?
    - `m[c(1), ]`
    - `m[c(2), c(1, 2)]`
    - `m[]`
    - `m[[2]]`

1. Suppose `df` is a data frame created with `data.frame(x=c(1,2,3), y=c("a","b","c"))`. What will each of the following operations return?
    - `df[c(1,2)]`
    - `df[c(1,2), c(2)]`
    - `df[['x']]`
    - `df[x]`
    - `df[[2]]`

1. Suppose `df` is a dataframe with column names `ageChild`, `ageParent`, and `dateAdded`. What will `df$age` return?  Explain why.

## Programming in R
1. Explain in one sentence the difference between a `for` loop and a `while` loop? 
